### ISSUE TITLE
Bug #1: Cannot remove multiple cards if one column is empty.

### ISSUE THREAD

**Issue by mattru** [cs361fall2017/team38#11]
Upon Pressing Remove it functions as intended and leaves the column empty:
![image](https://user-images.githubusercontent.com/32180935/31524544-22bd04aa-af6f-11e7-80c7-077eea830eb0.png)

Upon Pressing the other Remove, it does not remove the card.
![image](https://user-images.githubusercontent.com/32180935/31524595-9061098e-af6f-11e7-8a9d-7c5cfdd64e15.png)

**Comment by donaldjr** [comment]
I played around with it. It isn't outputting any column number when I click the column so it can't do anything. I even tried removing the if else statement and it still did not change.

**Comment by donaldjr** [comment]
![screenshot from 2017-10-12 17-47-07](https://user-images.githubusercontent.com/21960499/31525496-873cfd08-af75-11e7-8f9c-1b344f4fb9ba.png)

I attached a screenshot of the output in the web console. Still not sure what the problem could be.
